### ISSUE TITLE
Why force the use of a build step?

### ISSUE THREAD

**Issue by TotallyInformation** [DatatracCorporation/markdown-it-mermaid#3]
This module does not work with standard Node.js code - you cannot do a `require()` on it as you can with other markdown-it modules.

It seems strange to force people to have to include a build step with all of the complexities involved when it really isn't needed in most cases.

It would be great if you could add a suitable wrapper to allow the module to work with a standard require().

**Comment by JimPatterson** [comment]
Mermaid itself won't work with node.  It uses the DOM to build the SVG for the diagram.

**Comment by JimPatterson** [comment]
I just tried switch this code to not use import to avoid the build step, and mermaid uses import, so this is not something we can do at this time.
